Work.find_or_create_by(id: 1, name: 'ボウリング、バレーボール、社交ダンス（ワルツ、サンバ、タンゴ）、ピラティス、太極拳', cost: 3.0)
Work.find_or_create_by(id: 2, name: '自転車エルゴメーター（30～50 ワット）、自体重を使った軽い筋力トレーニング（軽・中等度）、体操（家で、軽・中等度）、ゴルフ（手ひきカートを使って）、カヌー',
                       cost: 3.5)
Work.find_or_create_by(id: 3, name: '全身を使ったテレビゲーム（スポーツ・ダンス）', cost: 3.8)
Work.find_or_create_by(id: 4, name: '卓球、パワーヨガ、ラジオ体操第 1', cost: 4.0)
Work.find_or_create_by(id: 5, name: 'やや速歩（平地、やや速めに＝93m/分）、ゴルフ（クラブを担いで運ぶ）', cost: 4.3)
Work.find_or_create_by(id: 6, name: 'テニス（ダブルス）＊、水中歩行（中等度）、ラジオ体操第 2', cost: 4.5)
Work.find_or_create_by(id: 7, name: '水泳（ゆっくりとした背泳）', cost: 4.8)
Work.find_or_create_by(id: 8, name: 'かなり速歩（平地、早く＝107m/分）、野球、ソフトボール、サーフィン、バレエ（モダン・ジャズ）', cost: 5.0)
Work.find_or_create_by(id: 9, name: '水泳（ゆっくりとした平泳ぎ）、スキー、アクアビクス', cost: 5.3)
Work.find_or_create_by(id: 10, name: 'バドミントン', cost: 5.5)
Work.find_or_create_by(id: 11, name: 'ゆっくりとしたジョギング、ウェイトトレーニング（高強度、パワーリフティング、ボディビル）、バスケットボール、水泳（のんびり泳ぐ）', cost: 6.0)
Work.find_or_create_by(id: 12, name: '山を登る（0～4.1Kg の荷物持って）', cost: 6.5)
Work.find_or_create_by(id: 13, name: '自転車エルゴメーター（90～100 ワット）', cost: 6.8)
Work.find_or_create_by(id: 14, name: 'ジョギング、サッカー、スキー、スケート、ハンドボール', cost: 7.0)
Work.find_or_create_by(id: 15, name: 'エアロビクス、テニス（シングルス）＊、山を登る（約 4.5～9.0Kg の荷物を持って）', cost: 7.3)
Work.find_or_create_by(id: 16, name: 'サイクリング（約 20 ㎏/時）', cost: 8.0)
Work.find_or_create_by(id: 17, name: 'ランニング（134m/分）、水泳（クロール、ふつうの速さ）', cost: 8.3)
Work.find_or_create_by(id: 18, name: 'ランニング（139m/分）', cost: 9.0)
Work.find_or_create_by(id: 19, name: 'ランニング（161m/分）', cost: 9.8)
Work.find_or_create_by(id: 20, name: '水泳（クロール、速い、69m/分）', cost: 10.0)
Work.find_or_create_by(id: 21, name: '武道・武術（柔道、柔術、空手、キックボクシング、テコンドー）', cost: 10.3)
Work.find_or_create_by(id: 22, name: 'ランニング（188m/分）、自転車エルゴメーター（161～200 ワット）', cost: 11.0)
Work.find_or_create_by(id: 23, name: 'ストレッチング、全身を使ったテレビゲーム（バランス運動、ヨガ）', cost: 2.3)
Work.find_or_create_by(id: 24, name: 'ヨガ、ビリヤード', cost: 2.5)
Work.find_or_create_by(id: 25, name: '座って行うラジオ体操', cost: 2.8)
